# Generated by Django 4.1.6 on 2023-02-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_phone_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='lte_exists',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='price',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='slug',
        ),
    ]
